name: myhino
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  #sdk: ">=2.7.0 <3.0.0" 
  sdk: '>=2.17.5 <3.0.0'


dependencies: 
  get_storage: ^2.0.3
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_svg: 1.1.0
  flutter_dotenv: ^5.0.2
  # flutter_login: ^4.0.0
  font_awesome_flutter: ^10.1.0 
  dio: ^4.0.6
  json_serializable: ^6.3.1

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/mobile/images/
    - assets/mobile/uploads/
    - .env
  uses-material-design: true

