name: myhino
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  get: ^4.6.5
  dio: ^4.0.6
  html: ^0.15.0
  intl: ^0.17.0 
  cool_alert: any

  get_storage: ^2.0.3
  cupertino_icons: ^1.0.2
  
  flutter_svg: 1.1.0
  flutter_dotenv: ^5.0.2
  font_awesome_flutter: ^10.1.0 
  
  json_serializable: ^6.3.1
  g_recaptcha_v3: ^0.0.5
  qr_code_scanner: ^1.0.0
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.1.1
  social_share: ^2.2.1
  url_launcher: ^6.1.5
  dropdown_search: ^5.0.2
  datetime_picker_formfield: ^2.0.1
  smart_select: ^4.3.2
  file_picker: ^5.0.1

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/mobile/images/
    - assets/mobile/uploads/
    - .env
  uses-material-design: true

